var data = [ { line: 1, variables: { one: undefined, two: 2 } },
  { line: 2, variables: { one: undefined, two: 2, four: 2 } },
  { line: 3, variables: { one: undefined, two: 2, four: 2, i: 0 } },
  { line: 4, variables: { one: undefined, two: 2, four: 2, i: 0 } },
  { line: 5, variables: { one: undefined, two: 2, four: 2, i: 0 } },
  { line: 3, variables: { one: undefined, two: 2, four: 2, i: 1 } },
  { line: 4, variables: { one: undefined, two: 2, four: 2, i: 1 } },
  { line: 5, variables: { one: undefined, two: 2, four: 2, i: 1 } },
  { line: 3, variables: { one: undefined, two: 2, four: 2, i: 2 } },
  { line: 4, variables: { one: undefined, two: 2, four: 2, i: 2 } },
  { line: 5, variables: { one: undefined, two: 2, four: 2, i: 2 } },
  { line: 3, variables: { one: undefined, two: 2, four: 2, i: 3 } },
  { line: 4, variables: { one: undefined, two: 2, four: 2, i: 3 } },
  { line: 5, variables: { one: undefined, two: 2, four: 2, i: 3 } },
  { line: 3, variables: { one: undefined, two: 2, four: 2, i: 4 } },
  { line: 4, variables: { one: undefined, two: 2, four: 2, i: 4 } },
  { line: 5, variables: { one: undefined, two: 2, four: 2, i: 4 } },
  { line: 3, variables: { one: undefined, two: 2, four: 2, i: 5 } },
  { line: 4, variables: { one: undefined, two: 2, four: 2, i: 5 } },
  { line: 5, variables: { one: undefined, two: 2, four: 2, i: 5 } },
  { line: 3, variables: { one: undefined, two: 2, four: 2, i: 6 } },
  { line: 4, variables: { one: undefined, two: 2, four: 2, i: 6 } },
  { line: 5, variables: { one: undefined, two: 2, four: 2, i: 6 } },
  { line: 3, variables: { one: undefined, two: 2, four: 2, i: 7 } },
  { line: 4, variables: { one: undefined, two: 2, four: 2, i: 7 } },
  { line: 5, variables: { one: undefined, two: 2, four: 2, i: 7 } },
  { line: 3, variables: { one: undefined, two: 2, four: 2, i: 8 } },
  { line: 4, variables: { one: undefined, two: 2, four: 2, i: 8 } },
  { line: 5, variables: { one: undefined, two: 2, four: 2, i: 8 } },
  { line: 3, variables: { one: undefined, two: 2, four: 2, i: 9 } },
  { line: 4, variables: { one: undefined, two: 2, four: 2, i: 9 } },
  { line: 5, variables: { one: undefined, two: 2, four: 2, i: 9 } },
  { line: 6, variables: { one: undefined, two: 2, four: 2, i: 10 } },
  { line: 7, variables: { one: undefined, two: 2, four: 2, i: 0 } },
  { line: 7, variables: { one: undefined, two: 2, four: 2, i: 1 } },
  { line: 7, variables: { one: undefined, two: 2, four: 2, i: 2 } },
  { line: 7, variables: { one: undefined, two: 2, four: 2, i: 3 } },
  { line: 7, variables: { one: undefined, two: 2, four: 2, i: 4 } },
  { line: 8, variables: { one: undefined, two: 2, four: 2, i: 5 } },
  { line: 11, variables: { one: undefined, two: 2, four: 2, i: 5 } },
  { line: 12, variables: { one: undefined, two: 2, four: 2, i: 5, what: 'what' } },
  { line: 13, variables: { one: undefined, two: 2, four: 2, i: 5, what: 'what', test: 'hello' } },
  { line: 14, variables: { one: undefined, two: 2, four: 2, i: 5, what: 'what', test: 'hello buddy' } },
  { line: 15,  variables: { one: undefined,two: 2, four: 2, i: 5, what: 'what', test: 'hello buddy', hello: 'hi' } } ]
//data is an array with objects
//
